### PR TITLE
Feature/fix readings service persistence

### LINKED ISSUE #151: Daily Office / Holy Eucharist readings "status" doesn't persist after changing Psalter Version or Translation
## Reproduction Steps

1.  Go to [https://www.dailyoffice2019.com/readings/morning_prayer/2024/2/17](https://www.dailyoffice2019.com/readings/morning_prayer/2024/2/17)
2. Select "Evening Prayer" under "Daily Offices"
3. Choose a different Psalter Version, such as "Traditional Psalms"

## Expected Results

When the page refreshes, "Evening Prayer" should still be selected.

## Actual Results

After refreshing, the service switches back to "Morning Prayer".

## Additional Information

The inverse is also true. If you choose "Evening Prayer", _then refresh the page_, it seems to then be locked to that service. Then, if you change it to "Morning Prayer" and choose something like a different Translation, once the page refreshes, it will go back to "Evening Prayer".

### PR DESCRIPTION
**Pull request by perryholden**
Fixes #151

### CODE REVIEW

File: app/src/router/index.js [hunk 1]
```diff
@@ -171,12 +171,21 @@ const routes = [
   { path: "/:pathMatch(.*)", component: PageNotFound, name: "not_found" },
 ];
 
+const routesToNotScrollToTop = [
```
Comment (perryholden) [inline app/src/router/index.js:174]: @blocher - I'll let you choose whether or not this is a good addition, but on changing the daily readings service, psalm styles, bible version, etc., it scrolled you to the top of the page. I find that a bit distracting when using this page. I'm making a constant here for those paths where we don't necessarily need a scroll to the top. Feel free to revert the commit that does this, however, if you disagree.

File: app/src/views/Readings.vue [hunk 2]
```diff
@@ -444,28 +460,25 @@ export default {
...
+      this.$router.push({
+        name: routeName,
+        params: {
+          service: serviceValues.service_name,
+          year: this.$route.params.year,
+          month: this.$route.params.month,
+          day: this.$route.params.day,
+          position: serviceValues.position
+        }
+      });
```
Comment (perryholden) [inline app/src/views/Readings.vue:481]: @blocher - This really is the core change. While I broke some logic off in a new function, this uses the router.push method to set the service value. This is important, because in the initialize() method, line 395, it looks for the service. While we updated the dynamically, it didn't necessarily change the route parameters. This changes it so that future calls to initialize() will remember the correct service value. I also tested this for those routes that do have a "position." Let me know if I can explain further.

File: app/src/router/index.js (hunk 1 above)
Comment (blocher) [reply app/src/router/index.js:174]: This is great. I've found this annoying

**Review by blocher — APPROVED** [review]
